/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Roteador implements Processador {
    public String getGreeting() {
        return "Hello world.";
    }

    public void processar(Mensagem msg) {
        if (msg.codigo % 2 == 0) {
            par.processar(msg);
        } else {
            impar.processar(msg);
        }
    }

    public Roteador(Processador par, Processador impar) {
        this.par = par;
        this.impar = impar;
    }

    private final Processador par;
    private final Processador impar;
}
