/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.List;
import java.util.ArrayList;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class RoteadorTest {
    @Test public void encaminhaMensagensParaOndeDeveEncaminhar() {
        Mensagem msgPar = new Mensagem(42, "não entre em panico");
        Mensagem msgImpar = new Mensagem(67, "elementar, meu caro watson");

        Processador processadorPar = mock(Processador.class);
        Processador processadorImpar = mock(Processador.class);

        Roteador roteador = new Roteador(processadorPar, processadorImpar);

        roteador.processar(msgPar);
        roteador.processar(msgImpar);

        verify(processadorPar).processar(msgPar);
        verify(processadorImpar).processar(msgImpar);
    }
}
